# Generated by Django 4.0.3 on 2022-03-19 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=50)),
                ('property_description', models.TextField()),
                ('partnership_proposal', models.TextField(max_length=155)),
                ('property_image', models.ImageField(upload_to='')),
                ('status_is_approved', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='signup.member')),
            ],
        ),
    ]
