# Generated by Django 4.0.3 on 2022-03-22 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signup', '0003_profile_whatsapp_number'),
        ('add', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_code', models.TextField()),
                ('partnership_report', models.TextField(null=True)),
                ('approve_connection', models.BooleanField(default=False)),
                ('partner1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member0', to='signup.member')),
                ('partner2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member1', to='signup.member')),
            ],
        ),
    ]
