# Generated by Django 4.0.3 on 2022-03-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whatsapp_number',
            field=models.IntegerField(default=785564315),
            preserve_default=False,
        ),
    ]
